fix(auth-provider): update auth-provider path (#481)
Looks like after moving the backends, this path needs to be updated to be able to perform the relative import

```
Error: Failed to get /openapi/v2 and /swagger.json: Cannot find module '../auth-providers/cmd.js'
Require stack:
- /Users/rsim/zendesk/scooter-ui/node_modules/kubernetes-client/backends/request/client.js
- /Users/rsim/zendesk/scooter-ui/node_modules/kubernetes-client/backends/request/index.js
- /Users/rsim/zendesk/scooter-ui/node_modules/kubernetes-client/lib/swagger-client.js
- /Users/rsim/zendesk/scooter-ui/node_modules/kubernetes-client/lib/index.js
- <repl>
    at /Users/rsim/zendesk/scooter-ui/node_modules/kubernetes-client/lib/swagger-client.js:57:15
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async <anonymous>:1:26
> }
```